const PREFIX = "APP";

export default {
  FETCH_DATA_SUCCESS: `${PREFIX}/FETCH_DATA_SUCCESS`,
  FETCH_DATA_FAILURE: `${PREFIX}/FETCH_DATA_FAILURE`,

  DELETE_DATA_SUCCESS: `${PREFIX}/DELETE_DATA_SUCCESS`,
  DELETE_DATA_FAILURE: `${PREFIX}/DELETE_DATA_FAILURE`
};
