# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.g ithub.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.10]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '12.10'
      uses: actions/setup-node@v1
      with:
        node-version: '12.10'
    - name: Install dependencies
      run: npm install
    - name: Start build
      run: npm run build --if-present
    env:
      CI: true
